### ISSUE TITLE
What are the restrictions on chaining select methods?

### ISSUE THREAD

**Issue by anentropic** [facebookincubator/Bowler#118]
The readme appears to say you can make a query that has a `select` followed by filters and modifiers, then chain a subsequent `select` onto it:
https://github.com/facebookincubator/Bowler/tree/master/bowler#query-reference

When I try to do this I get an error:
```
  File "/.virtualenvs/waterloo-sHXra0II/lib/python3.7/site-packages/bowler/tool.py", line 209, in refactor_queue
    hunks = self.refactor_file(filename)
  File "/.virtualenvs/waterloo-sHXra0II/lib/python3.7/site-packages/bowler/tool.py", line 171, in refactor_file
    tree = self.refactor_string(input, filename)
  File "/.virtualenvs/waterloo-sHXra0II/lib/python3.7/site-packages/fissix/refactor.py", line 370, in refactor_string
    self.refactor_tree(tree, name)
  File "/.virtualenvs/waterloo-sHXra0II/lib/python3.7/site-packages/fissix/refactor.py", line 410, in refactor_tree
    self.traverse_by(self.bmi_post_order_heads, tree.post_order())
  File "/.virtualenvs/waterloo-sHXra0II/lib/python3.7/site-packages/fissix/refactor.py", line 488, in traverse_by
    node.replace(new)
  File "/.virtualenvs/waterloo-sHXra0II/lib/python3.7/site-packages/fissix/pytree.py", line 108, in replace
    assert self.parent is not None, str(self)
AssertionError
```

I am guessing that this is because the subsequent selector has to select some sub-element of what was already selected by the initial `select`?  You can't chain an unrelated select query on?

(I wanted to do that because I am naïvely trying to pass metadata about the current file between  my modifiers)

**Comment by thatch** [comment]
Can you share a concrete example?  Normally you have one select, zero or more filters, and one modify.  Then repeat.  The error you're hitting is in fissix, and probably has something to do with the first modifier's replacement value, rather than the chained selects...

Are you replacing nodes directly with synthesized versions, rather than calling .replace on them?  If so you need to also set the parent yourself.

**Comment by anentropic** [comment]
I do a select like:
```python
        .select(
            r"""
            funcdef<
                'def' function_name=any
                any* ':'
                suite< '\n'
                    initial_indent_node=(%s)
                    docstring_parent_node=simple_stmt< any* >
                    any*
                >
            >
            """ % indent_patterns
        )
```

I couldn't work out how to select exactly what I wanted via the pattern language so then in a `filter` step I do:
```python
    try:
        docstring_node = capture['docstring_parent_node'].children[0]
        result: bool = is_docstring(docstring_node.value)  # hacky regex test
    except (AttributeError, IndexError):
        return False
    capture['docstring_node'] = docstring_node
    return result
```
then in the modifier function I'm using `.replace`, but not on the `node` passed to the method but the other one I stuffed into the `capture` dict in the filter above:
```python
capture['docstring_node'].replace(new_docstring_node)
```

I will try some experiments on multiple selects without doing any node replacement to see if that is the problem

**Comment by thatch** [comment]
I don't quite understand your goal, but if you want to match docstrings, that's actually any string that's the first statement inside a function (etc); it doesn't actually have to be triple-quoted.

You can use a selector like

```
funcdef <
  "def" name=any
  any* ":"
  suite < "\n"
    indent=any
    simple_stmt < docstring=STRING any* >
    any*
  >
>
```

`STRING` is not well-documented, but you can find some examples in lib2to3 fixers or use `bowler dump <filename>` to print the leaf types.  This selector is still a bit specific, because it doesn't match functions on a single line, nor class or method docstrings.

I'll leave this open a while in case this doesn't solve it for you; please give a more complete repro if you continue to have trouble.

**Comment by anentropic** [comment]
thanks very much for your help, the selector you gave is better than what I was using and does exactly what I want

I tried some experiments with multiple selectors and didn't hit the AssertionError again so will close this issue
