### ISSUE TITLE
Tool with one arg uses one process

### ISSUE THREAD

**Issue by thatch** [facebookincubator/Bowler#69]
There's a bug on https://github.com/facebookincubator/Bowler/blob/master/bowler/tool.py#L214 when used with refactor_dir; it takes the count of args as number of processes.  This doesn't hit the case of `bowler run foo.py $(find . -name '*.py')` which is how I normally do it.  Removing the min is the easiest way forward.

**Comment by jreese** [comment]
Maybe the correct solution is to drop the need for `refactor_dir`, and pre-emptively explode the set of inputs, dedupe and filter them appropriately with `filename_matcher`, and *then* decide how many processes to spin up and then queue the work items.  It would actually reduce the number of code paths, because we could replace `refactor_dir` with `NotImplementedError` and only ever process a set of file paths.

**Comment by thatch** [comment]
As long as you don't have an intention of moving to a bounded queue, I think we could do something like this to just move the starting of threads down a bit, at which point we've expanded dirs into files... https://github.com/facebookincubator/Bowler/compare/master...thatch:issue69

**Comment by jreese** [comment]
That works for me too 😆
